name: FirstExampleInDocs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
        image: dlwoodruff/c2fcondatest:latest
        env:
          PATH: /opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      - uses: actions/checkout@v2

      - name: make C++
        run: |
          cd src/Cell2Fire/Cell2FireC
          make
      - name: setup the program
        run: |
          cd src
          python setup.py develop

      - name: create input data
        run: |
           cd src/Cell2Fire
           python main.py --input-instance-folder ../../data/Sub40x40/ --output-folder ../../results/Sub40x40 --ignitions --sim-years 1 --nsims 5 --finalGrid --weather rows --nweathers 1 --Fire-Period-Length 1.0 --output-messages --ROS-CV 0.0 --seed 123 --stats --allPlots --IgnitionRad 5 --grids --combine

      - name: run tests
        run: |
          cd src/Cell2Fire
          python test_xxxx.py
          # DLW: use pytest (see mape-maker)
          # everyone else: add your test here for now...
